# Generated by Django 4.1.6 on 2023-02-14 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=64, unique=True)),
                ('summary', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False, verbose_name='Task completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
